### ISSUE TITLE
UserWarning: stft will soon require the return_complex parameter be given for real inputs

### ISSUE THREAD

**Issue by yijingshihenxiule** [facebookresearch/BinauralSpeechSynthesis#4]
Hello,when I run the train.py, there is always a warning:

` UserWarning: stft will soon require the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release. (Triggered internally at  /pytorch/aten/src/ATen/native/SpectralOps.cpp:639.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore`

then nothing else.

Could you help me solve it?

**Comment by alexanderrichard** [comment]
Hi! This warning is new in pytorch 1.8 which you probably use. You can ignore it, the training will still run. In future versions of pytorch, you will need to convert the stft complex result to it's two-channel float version via ```th.view_as_real(spec)``` after this line https://github.com/facebookresearch/BinauralSpeechSynthesis/blob/main/src/utils.py#L175

**Comment by yijingshihenxiule** [comment]
Thank you for your reply, @alexanderrichard . What I used is pytorch 1.8.1 and  Nvidia 1080ti GPU. It always stay in the first warning. Maybe it will cost more time. I am looking forward to  your subsequent work!

**Comment by alexanderrichard** [comment]
FYI: Pre-trained models are now available, see the updated readme.
Did you resolve your problem? As I said, running the first epoch might just take quite a while depending on your hardware.

**Comment by zhexian949** [comment]
Hi， @alexanderrichard . Thank you for your answering. I solved it and run successfully.
I will read the pretrained model later! Thanks!

**Comment by zhexian949** [comment]
Hi， @alexanderrichard . Thank you for your answering. I solved it and run successfully.
I will read the pretrained model later! Thanks!

**Comment by yijingshihenxiule** [comment]
Hi, @alexanderrichard . I have accessed the other work of yours`IMPLICIT HRTF MODELING USING TEMPORAL CONVOLUTIONAL NETWORKS`. But the code seems like to be unreleased. I would like to know whether it can be released. Could you help me? Thank you.

**Comment by alexanderrichard** [comment]
Hi, please reach out to the main author of that paper with that question. This is the codebase for another paper, you seem to be in the wrong repository.
